[package]
name = "motoko-rts-macros"
version = "0.1.0"
authors = ["dfinity <sdk@dfinity.org>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.66"
syn = { version = "1.0.107", features = ["full"] }
quote = "1.0.23"
