[package]
name = "motoko-rts-macros"
version = "0.1.0"
authors = ["dfinity <team-motoko@dfinity.org>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.78"
syn = { version = "2.0.52", features = ["full"] }
quote = "1.0.23"
