[package]
name = "wasm-profiler"
version = "0.1.1"
edition = "2018"

[dependencies]
parity-wasm = { version = "0.45.0", features = ["std", "sign_ext", "bulk"] }
structopt = "0.3"
clap = "2.33"

[[bin]]
name = "wasm-profiler-instrument"
path = "src/wasm_profiler_instrument.rs"
