[package]
name = "motoko-rts"
version = "0.1.0"
authors = ["dfinity <sdk@dfinity.org>"]
edition = "2018"

[lib]
crate-type = ["rlib"]
path = "../src/lib.rs"

[dependencies]
motoko-rts-macros = { path = "../../motoko-rts-macros" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
